server:
  port: 8600

spring:
  application:
    name: first-zuul
    version: v1.0.1
#提供者name
eureka_provider: first-provider

eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.application.version}:${server.port}
    appname: ${spring.application.name}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka

zuul:
  routes:
    api-1:
      path: /api/v1/**
      service-id: first-invoker
    api-2:
      path: /api/v2/**
      service-id: first-invoker