server:
  port: 8800

spring:
  application:
    name: first-invoker
    version: v1.0.1
#提供者name
eureka_provider: first-provider

eureka:
  instance:
    instance-id: ${spring.application.name}-${spring.application.version}:${server.port}
    appname: ${spring.application.name}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka

feign:
  hystrix:
    #开启熔断
    enabled: true