server:
  port: 8761
spring:
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: 1qaz2wsx
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
